<footer class="">
    <h4 class="">ici vous pouvez voir les modifications apporter directement sur le site</h4>
    <div class=""> <!-- Utilisez d-flex, justify-content-between et align-items-center -->

    </div>

    <nav class="">
        <ul class="">
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/">Accueil</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/prestations">prestations</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/formulaire-de-renseignement">formulaire de renseignement</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/contact">me trouver</a>
            </li>
        </ul>
    </nav>
</footer>
