<div class=""> <!-- Ajoutez un conteneur pour centrer le contenu -->
    <div class=""> <!-- Utilisez d-flex, justify-content-between et align-items-center -->
        <h1><a class="" href="/ProjetFinal_LaetitiaNailArts/">Panneau de Controle Laetitia Nails Art</a></h1>
            <!-- Lien pour la déconnexion -->
            <a class="" href="/ProjetFinal_LaetitiaNailArts/deconnexion">Déconnexion</a>
    </div>
    <nav class=""> <!-- Utilisation de flex-column -->
        <ul class=""> <!-- Supprimez ml-auto pour que les éléments soient centrés -->
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/dashboard">Accueil</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-admin">Admin</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-utilisateurs">Utilisateurs</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-prestations">Prestations</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/list-categories">Catégories</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-formulaire">formulaires</a>
            </li>
            <li class="">
                <a class="" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-contact">page contact</a>
            </li>
        </ul>
    </nav>
</div>