<div class="container"> <!-- Ajoutez un conteneur pour centrer le contenu -->
    <div class="d-flex justify-content-between align-items-center"> <!-- Utilisez d-flex, justify-content-between et align-items-center -->
        <h1><a class="navbar-brand" href="/ProjetFinal_LaetitiaNailArts/">Panneau de Controle Laetitia Nails Art</a></h1>
            <!-- Lien pour la déconnexion -->
            <a class="btn btn-danger" href="/ProjetFinal_LaetitiaNailArts/deconnexion">Déconnexion</a>
    </div>
    <nav class="navbar navbar-expand-lg bg-light px-3 flex-column"> <!-- Utilisation de flex-column -->
        <ul class="navbar-nav"> <!-- Supprimez ml-auto pour que les éléments soient centrés -->
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/admin/dashboard">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-admin">Admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-utilisateurs">Utilisateurs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/admin/gerer-prestations">Prestations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/admin/list-categories">Catégories</a>
            </li>
        </ul>
    </nav>
</div>