<main class="container py-5">
    <h2 class="mb-5">Connexion au panneau de controle</h2>
    <form method="post" action="/ProjetFinal_LaetitiaNailArts/check-admin-connexion" class="col-6">
        <input type="hidden" name="formName" id="formName" value="adminLoginForm" />
        <fieldset class="mb-3">
            <label for="username" class="form-label">Nom d'utilisateur</label>
            <input type="text" name="username" id="username" class="form-control" required>
        </fieldset>
        <fieldset class="mb-3">
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" name="password" id="password" class="form-control" required>
        </fieldset>
        <button type="submit" class="btn btn-primary">Se Connecter</button>
    </form>
</main>