<main class="container-sm">
    <?php
    // Vérifiez s'il y a un message d'erreur
    if (isset($_SESSION['success_message'])) {
        echo '<div class="fade-out-message">' . $_SESSION['success_message'] . '</div>';
        unset($_SESSION['success_message']); // Supprime le message de la session
    }

    // Vérifiez s'il y a un message de succès
    if (isset($_SESSION['error_message'])) {
        echo '<div class="fade-out-message">' . $_SESSION['error_message'] . '</div>';
        unset($_SESSION['error_message']); // Supprime le message de la session
    }
    ?>
    <section>
        <h3 class="p-4">Mise à jour de l'Adresse</h3>
        <h4 class="">adresse actuelle :</h4>
        <?php foreach ($data['contactInfo'] as $contact): ?>
            <p class=""><?= $contact->getAdresse(); ?></p>
            <p class=""><?= $contact->getCodePostal(); ?> <?= $contact->getVille(); ?></p>
        <?php endforeach; ?>
        <form method="POST" action="/ProjetFinal_LaetitiaNailArts/admin/update-address">
            <div class="form-group">
                <label for="adresse">Adresse</label>
                <input type="text" class="form-control" id="adresse" name="adresse" required>
            </div>
            <div class="form-group">
                <label for="code_postal">Code Postal</label>
                <input type="text" class="form-control" id="code_postal" name="code_postal" required>
            </div>
            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" class="form-control" id="ville" name="ville" required>
            </div>
            <button type="submit" class="btn btn-primary">Mettre à Jour</button>
        </form>
    </section>

    <button id="scrollToTopBtn" class="scrollToTopBtn" style="display: none;position: fixed; bottom: 20px; right: 20px">
        <i class="fas fa-arrow-up"></i>
    </button>

    <section>
        <h3 class="">Mise à jour de l'URL Google Maps</h3>
        <h4 class="">url de géolocalisation actuelle :</h4>
        <?php foreach ($data['contactInfo'] as $contact): ?>
            <p class=""><?= htmlspecialchars_decode($contact->getUrlGeo()); ?></p>
        <?php endforeach; ?>
        <form method="POST" action="/ProjetFinal_LaetitiaNailArts/admin/update-url-geo">
            <div class="form-group">
                <label for="url_geo">URL Google Maps</label>
                <input type="text" class="form-control" id="url_geo" name="url_geo" required>
            </div>
            <button type="submit" class="btn btn-primary">Mettre à Jour</button>
        </form>
    </section>

    <section>
        <h3 class="">Mise à jour des Numéros de Téléphone</h3>
        <h4 class="">numéro de telephone actuelle :</h4>
        <?php foreach ($data['contactInfo'] as $contact): ?>
            <p class=""><?= $contact->getNumeroFixe(); ?></p>
            <p class=""><?= $contact->getNumeroPortable(); ?></p>
        <?php endforeach; ?>
        <form method="POST" action="/ProjetFinal_LaetitiaNailArts/admin/update-phone-numbers">
            <div class="form-group">
                <label for="numero_fixe">Numéro Fixe</label>
                <input type="text" class="form-control" id="numero_fixe" name="numero_fixe" required>
            </div>
            <div class="form-group mb-2">
                <label for="numero_portable">Numéro Portable</label>
                <input type="text" class="form-control" id="numero_portable" name="numero_portable" required>
            </div>
            <button type="submit" class="btn btn-primary">Mettre à Jour</button>
        </form>
    </section>
</main>