<footer class="">
    <div class="">
        <div class="footer-section">
            <p><a href="/ProjetFinal_LaetitiaNailArts/conditions-generales" class="text-white">Conditions générales d'utilisation</a></p>
        </div>
    </div>
    <div class="">
        <div class="footer-section text-center">
            <!-- Logo -->
            <img src="votre-logo.png" alt="Votre Logo">
            <p>&copy; MikeDev35</p>
        </div>
    </div>
    <div class="">
        <div class="footer-section text-right">
            <ul class="social-media">
                <li class=""><a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></a></li>
                <li class=""><a href="https://twitter.com/?lang=frinsta" target="_blank"><i class="fab fa-twitter"></i></a></li>
                <li class=""><a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
    </div>
</footer>