<header>
    <div class="header-content">
        <div class="h1-replacement-image">
            <a href="/ProjetFinal_LaetitiaNailArts/">
            <img src="/ProjetFinal_LaetitiaNailArts/assets/images/logo/laetitiafashionails.webp" alt="">
            </a>
        </div>
        <h1><a href="/ProjetFinal_LaetitiaNailArts/">Laetitia Nails Art</h1>
        <button class="desktop-login-button">
            <a class="" href="/ProjetFinal_LaetitiaNailArts/connexion">Connexion</a>
        </button>
        <div class="burger-menu">
            <i class="fas fa-bars"></i>
        </div>
    </div>
    <nav>
        <ul class="nav-links">
            <li><a href="/ProjetFinal_LaetitiaNailArts/">accueil</a></li>
            <li><a href="/ProjetFinal_LaetitiaNailArts/prestations">prestations</a></li>
            <li><a href="/ProjetFinal_LaetitiaNailArts/formulaire-de-renseignement">formulaire de renseignement</a></li>
            <li><a href="/ProjetFinal_LaetitiaNailArts/contact">me trouver</a></li>
            <li><a href="/ProjetFinal_LaetitiaNailArts/creer-un-compte">Créer un compte</a></li>
            <!-- Ajouter un élément <li> pour le bouton de connexion en version mobile -->
            <li class="mobile-login-button"><a class="" href="/ProjetFinal_LaetitiaNailArts/connexion">Connexion</a></li>
        </ul>
    </nav>
</header>