<main class="">
    <h2 class="">Conditions Générales d'Utilisation</h2>
    <section>
        <h3>1. Introduction</h3>
        <p>Ceci est une introduction aux conditions générales d'utilisation de notre site web.</p>
    </section>

    <section>
        <h3>2. Utilisation du site</h3>
        <p>En utilisant notre site, vous acceptez de respecter les règles suivantes :</p>
        <ul>
            <li>Vous ne pouvez pas utiliser notre site à des fins illégales.</li>
            <li>Vous ne pouvez pas partager de contenu offensant.</li>
            <li>Votre utilisation du site est soumise à notre politique de confidentialité.</li>
        </ul>
    </section>

    <section>
        <h3>3. Confidentialité</h3>
        <p>Notre politique de confidentialité explique comment nous collectons, utilisons et protégeons vos informations personnelles. En utilisant notre site, vous acceptez cette politique.</p>
    </section>

    <section>
        <h3>4. Droits de propriété intellectuelle</h3>
        <p>Tout le contenu de ce site, y compris le texte, les images, les vidéos, les logos, etc., est protégé par des droits d'auteur. Vous ne pouvez pas reproduire, distribuer ou utiliser ce contenu sans autorisation.</p>
    </section>

    <section>
        <h3>5. Modifications des CGU</h3>
        <p>Nous nous réservons le droit de modifier ces conditions générales d'utilisation à tout moment. Les modifications entreront en vigueur dès leur publication sur le site. Il est de votre responsabilité de les consulter régulièrement.</p>
    </section>

    <section>
        <h3>6. Contact</h3>
        <p>Pour toute question ou préoccupation concernant nos conditions générales d'utilisation, veuillez nous contacter à l'adresse suivante : <a href="mailto:contact@votresite.com">contact@votresite.com</a>.</p>
    </section>
</main>