<main class="">
    <h2 class="">bonjour et bienvenue dans mon salon</h2>
    <section class="">
        <div class="">
            <img src="/ProjetFinal_LaetitiaNailArts/assets/images/portrait.jpg" alt="Portrait d'une jeune femme de type caucasienne généré par IA" class="img-fluid">
        </div>
        <div class="">
            <div>
                <h3 class="">Laetitia : L'Art de la Beauté des Ongles</h3>
                <p>Je suis Laetitia, et je suis ravie de partager avec vous mon parcours passionnant dans le monde de la beauté des ongles. Récemment diplômée en manucure, j'ai dédié ma vie à combiner ma passion avec mon travail.
                <br>Depuis mon plus jeune âge, la beauté et la créativité m'ont toujours captivée. J'ai consacré d'innombrables heures à perfectionner mes compétences en manucure, à suivre les dernières tendances et à créer des designs uniques. Je suis une artiste de l'ongle, et chaque manucure que je réalise est une œuvre d'art personnalisée.</p>
                <p>Ce qui rend mon approche unique, c'est que je suis heureuse de m'occuper également des hommes qui le désirent. La beauté des ongles n'a pas de genre, et je crois en l'importance de se sentir bien dans sa peau, quel que soit son sexe.
                <br>Avec mon diplôme en main, je suis prête à vous offrir des résultats impeccables et à sublimer la beauté naturelle de vos ongles, que vous soyez homme ou femme. Mon avenir dans le monde de la beauté des ongles s'annonce prometteur, et je suis impatiente de partager ma passion avec vous tous.</p>
                <p>Merci de m'avoir écoutée. Je suis convaincue que nous partagerons une aventure incroyable dans le monde de la beauté des ongles, en mettant en avant la diversité et l'authenticité,<br>Laetitia</p>
            </div>
        </div>
    </section>
    <section class="">
        <div class="">
            <h3 class="">Bienvenue dans mon Salon à Domicile : Cosy et Smooth</h3>
            <p>Je suis ravie de vous inviter dans mon salon à domicile. Mon objectif est de créer une expérience de beauté des ongles unique, alliant confort et relaxation et de rigueur en matière d'hygiène.
            <br>Mon salon a été aménagé avec soin pour vous offrir une atmosphère cosy et douillette. Dès que vous franchirez la porte, vous serez accueillis dans un espace chaleureux et apaisant. Les couleurs apaisantes, la musique douce et l'éclairage tamisé créent une ambiance propice à la détente.</p>
            <p>En ce qui concerne l'hygiène, je tiens à souligner que la santé et la sécurité de mes clients sont ma priorité absolue. Je suis strictement conforme aux normes d'hygiène et de stérilisation recommandées par les autorités sanitaires. Tous les outils et les équipements sont nettoyés et désinfectés après chaque utilisation. Les produits que j'utilise sont de haute qualité et sont également choisis avec soin pour leur sécurité.
             <br>L'un des avantages de mon salon à domicile est la personnalisation. Je m'efforce de connaître chaque client et de comprendre ses préférences. Cela me permet de créer des expériences sur mesure, en accord avec vos goûts et besoins individuels.</p>
            <p>Chaque rendez-vous dans mon salon est une pause bien-être. Vous pourrez vous détendre, vous recentrer et profiter d'un moment de tranquillité pendant que je m'occupe de sublimer vos ongles.
            <br>En résumé, mon salon à domicile est un endroit où le confort et la douceur se rejoignent pour créer une expérience de beauté des ongles inoubliable. Je suis impatiente de vous accueillir dans cet espace et de vous offrir un moment de détente tout en prenant soin de vos ongles.</p>
            <p>Au plaisir de vous recevoir bientôt,<br>laetitia</p>
        </div>
        <div class="">
            <img src="/ProjetFinal_LaetitiaNailArts/assets/images/interieur-salon.jpg" alt="image d'un salon pris sur instagram avec l'accord" class="img-fluid">
        </div>
    </section>
    <secction class="">
        <div class="">
            <img src="/ProjetFinal_LaetitiaNailArts/assets/images/ongle-et-nature.jpg" alt="image pris sur iStock montrant des mains vernis avec une feuille d'arbre verte" class="img-fluid">
        </div>
        <div class="">
            <div class="">
                <h3 class="">Laetitia : La Beauté des Ongles Naturelle</h3>
                <p>Mon engagement premier est de vous offrir une expérience de beauté des ongles authentique grâce à l'utilisation exclusive de produits d'origine naturelle en provenance de France et d'Europe.
                    <br>Chacun des produits que j'utilise est sélectionné avec soin pour sa qualité exceptionnelle, tout en respectant votre santé et notre environnement. Mon approche met l'accent sur la naturalité, la sécurité et le respect de la nature.</p>
                <p>Mon objectif est de sublimer vos ongles tout en préservant leur santé, en utilisant des produits qui correspondent à des normes éthiques élevées. Chaque rendez-vous est une opportunité de vous offrir un soin des ongles exceptionnellement naturel.
                    <br>En résumé, je suis déterminée à vous offrir une expérience de beauté des ongles où la naturalité est au cœur de tout. Vous pourrez profiter d'un moment de détente tout en prenant soin de vos ongles de manière respectueuse de la nature.</p>
                <p>Je suis impatiente de vous accueillir et de vous montrer comment la beauté et la naturalité peuvent se rejoindre harmonieusement.</p>
                <p>Au plaisir de vous recevoir bientôt,<br>laetitia</p>
            </div>
        </div>
    </secction>
</main>