<?php
if(isset($this->data["message"]) && $this->data["message"][1] === "general") //* Si on à un message dans la data
{
    ?>
    <span class="success"><?=$this->data["message"][0]; ?></span>
    <?php
}
?>
<main class="container py-5">
    <h2 class="mb-5">Créer un compte</h2>
    <form method="post" action="/ProjetFinal_LaetitiaNailArts/check-creer-un-compte" id="registerForm" class="col-4">
    <input type="hidden" name="formName" id="formName" value="registerForm" />
        <fieldset class="mb-3">
            <label for="username" class="form-label">
                Nom d'utilisateur
            </label>
            <input type="text" name="username" id="username" class="form-control" required />
            <span id="error_username"><?php
                if(isset($this->data["message"]) && $this->data["message"][1] === "username")
                {
                    echo $this->data["message"][0];
                }
                ?></span>
        </fieldset>
        <fieldset class="mb-3">
            <label for="email" class="form-label">
                Email
            </label>
            <input type="email" name="email" id="email" class="form-control" required />
            <span id="error_email"><?php
                if(isset($this->data["message"]) && $this->data["message"][1] === "email")
                {
                    echo $this->data["message"][0];
                }
                ?></span>
        </fieldset>
        <fieldset class="mb-5">
            <label for="password" class="form-label">
                Mot de passe
            </label>
            <input type="password" name="password" id="password" class="form-control" required />
            <span id="error_password"><?php
                if(isset($this->data["message"]) && $this->data["message"][1] === "password")
                {
                    echo $this->data["message"][0];
                }
                ?></span>
        </fieldset>
        <fieldset class="mb-5">
            <label for="confirmPassword" class="form-label">
                Confirmation du Mot de passe
            </label>
            <input type="password" name="confirmPassword" id="confirmPassword" class="form-control" required />
            <span id="error_confirm_password"><?php
                if(isset($this->data["message"]) && $this->data["message"][1] === "confirm_password")
                {
                    echo $this->data["message"][0];
                }
                ?></span>
        </fieldset>
        <button type="submit" class="btn btn-primary">Créer un compte</button>
    </form>
</main>
<script type="module" src="../../assets/js/register.js"></script>