<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laetitia Nails Art</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <header>
        <!-- Insérer le contenu de l'en-tête ici -->
        <?php
            if (isset($_SESSION["role"])) {
                if ($_SESSION["role"] === "admin") {
                require 'admin/_header.phtml'; // Accès administrateur
                } else {
                require 'user/_header.phtml'; // Accès utilisateur
                }
            } else {
                require 'guess/_header.phtml'; // Accès visiteurs
            }
        ?>
    </header>
    
    <?php require "templates/{$page}.phtml"; ?>
    
    <footer>
        <!-- Insérer le contenu du pied de page ici -->
        <p>&copy; <?= date('Y') ?> Votre entreprise. Tous droits réservés.</p>
    </footer>
    
    <script src="assets/js/main.js"></script>
</body>
</html>
