<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laetitia Nails Art</title>
    <link rel="icon" href="/ProjetFinal_LaetitiaNailArts/assets/images/logo/laetitiafashionails-fav.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="/ProjetFinal_LaetitiaNailArts/assets/styles/css/style.css" type="text/css">
    <link rel="stylesheet" href="/ProjetFinal_LaetitiaNailArts/assets/styles/css/mediaqueries.css" type="text/css">
</head>
<body>
    <header>
        <!-- Insérer le contenu de l'en-tête ici -->
        <?php
            if (isset($_SESSION["role"])) {
                if ($_SESSION["role"] === "admin") {
                require 'admin/_header.phtml'; // Accès administrateur
                } else {
                require 'user/_header.phtml'; // Accès utilisateur
                }
            } else {
                require 'guess/_header.phtml'; // Accès visiteurs
            }
        ?>
    </header>
    
    <?php require "templates/{$page}.phtml"; ?>
    
    <footer>
        <!-- Insérer le contenu du footer ici -->
        <?php
        if (isset($_SESSION["role"])) {
            if ($_SESSION["role"] === "admin") {
                require 'admin/_footer.phtml'; // Accès administrateur
            } else {
                require 'user/_footer.phtml'; // Accès utilisateur
            }
        } else {
            require 'guess/_footer.phtml'; // Accès visiteurs
        }
        ?>
    </footer>
    
    <script src="/ProjetFinal_LaetitiaNailArts/assets/js/main.js" type="module"></script>
</body>
</html>
