<header>
    <div class="d-flex justify-content-between align-items-center"> <!-- Utilisez d-flex, justify-content-between et align-items-center -->
        <h1><a class="navbar-brand" href="/ProjetFinal_LaetitiaNailArts/">Laetitia Nails Art</a></h1>
        <!-- Lien pour la déconnexion -->
        <a class="btn btn-danger" href="/ProjetFinal_LaetitiaNailArts/deconnexion">Déconnexion</a>
    </div>
    <nav class="navbar navbar-expand-lg bg-light px-3">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/prestations">prestations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ProjetFinal_LaetitiaNailArts/mon-compte">Mon Compte</a>
            </li>
        </ul>
    </nav>
</header>